###################################################################
#                                                                 #
#  Дополнительные настройки проекта для непрерывной интеграции.   #
#  В общем случае должны быть установлены в значения по умолчаню  #
#                                                                 #
###################################################################

variables:

  # По умолчаню: ON
  CODE_COVERAGE: "ON"

  # включить максимум предупреждений (как -Werror) при сборки для master
  # По умолчаню: ON
  PARANOID_WARNING: "ON"

  # По умолчаню: ON
  EXTRA_WARNINGS: "ON"

  # По умолчаню: OFF
  BUILD_SHARED_LIBS: "OFF"

  # По умолчаню: ON
  BUILD_TESTING: "ON"

  # Позволить собмодулям опережать свою master-ветку 
  # По умолчаню: OFF
  ALLOW_AHEAD_MASTER: "ON"
