#!/bin/bash
script_name=$(readlink -e $0)
script_dir=$(dirname $script_name)
curdir=$script_dir/../..

name=$1
branch=$2
if [ -z $branch ]; then
  branch=master
fi

pushd `pwd`
cd $curdir
rm -rf $name
git clone http://github.lan/cpp/$name.git
cd $name
git checkout $branch
mkdir build

cd build
cmake ..
cmake --build .
popd
