name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: sudo apt-get install -y valgrind
    - name: init
      run: mkdir -p build
    - name: configure
      run: cd build && cmake .. -DBUILD_TESTING=ON -DPARANOID_WARNINGS=OFF
    - name: make
      run: cmake --build ./build
    - name: make check
      run: cd build && ctest
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
