name: Create Pull Request
on:
  repository_dispatch:
    types: [create-pull-request]
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create Pull Request
        id: cpr
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: mambaru
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
