name: C++ CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        sudo locale-gen ru_RU
        sudo locale-gen ru_RU.UTF-8
        mkdir -p build
    - name: configure
      run: cd build && cmake .. -DBUILD_TESTING=ON -DPARANOID_WARNINGS=OFF -DNO_MEMCHECK=ON
    - name: make
      run: cmake --build ./build
    - name: make check
      run: cd build && ctest
