###################################################################
# TODO:                                                           #
# Ахтунг: для сборок должна быть папка daemon                     #
###################################################################

.build_template:
  stage: build
  script:
    - echo "CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME"
    - echo ${BLDIR}
    - echo "if [[ ${GC} == ON ]]; then rm -rf ${BLDIR}; fi"
    - if [[ "${GC}" == "ON" ]]; then rm -rf "${BLDIR}"; fi
    - ./external/cmake-ci/scripts/build-and-test.sh
    - if [[ "$GC" == "ON" ]]; then rm -rf "${BLDIR}"; fi
  except:
    - schedules

basic:
  extends:
    - .build_template
    - .basic
  before_script:
    - export CXX_STANDARD=${DISTRIB_STANDARD} CXX_COMPILER=${DISTRIB_COMPILER} BUILD_TYPE=${BASIC_BUILD_TYPE} PARANOID_WARNING="OFF"
    - export BLDIR="BasicBuild" CMAKE_ARGS=""

draft:
  extends:
    - .build_template
    - .draft
  before_script:
    - export CXX_STANDARD=${DISTRIB_STANDARD} CXX_COMPILER=${DISTRIB_COMPILER} BUILD_TYPE=${DISTRIB_DRAFT} PARANOID_WARNING="OFF" DISABLE_WARNINGS="ON" BUILD_TESTING="OFF"
    - export BLDIR="DraftBuild" CMAKE_ARGS=""

hotfix:
  extends:
    - .build_template
    - .hotfix
  before_script:
    - export CXX_STANDARD=${DISTRIB_STANDARD} CXX_COMPILER=${DISTRIB_COMPILER} BUILD_TYPE=${DISTRIB_DRAFT} PARANOID_WARNING="OFF" EXTRA_WARNINGS="OFF"
    - export BLDIR="HotfixBuild" CMAKE_ARGS=""

cppcheck:
  stage: cppcheck
  extends:
    - .cppcheck
  script:
    - echo "Статический анализ кода ${SCRIPTS}/cppcheck-ci.sh"
    - ${SCRIPTS}/cppcheck-ci.sh

